version: '3.8'

services:
  vocab-service:
    build: .
    ports:
      - '25001:25001'
    container_name: vocab-service
    networks:
      - concifora_default
networks:
  concifora_default:
    external: true