server:
  port: 25001

spring:
  datasource:
    url: ${VOCAB_DB_URL}
    username: ${POSTGRE_USERNAME}
    password: ${POSTGRE_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public

  data:
    redis:
      host: localhost
      port: 6379