server:
  port: 25001

spring:
  datasource:
    url: ${VOCAB_DB_URL}
    username: ${POSTGRE_USERNAME}
    password: ${POSTGRE_PASS}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public

  data:
    redis:
      host: localhost
      port: 6379

parser:
  api:
    ninjas:
      base-url: https://api.api-ninjas.com
      header:
        key-name: X-Api-Key
        key-value: ${NINJAS_KEY}
      endpoints:
        dictionary: /v1/dictionary
        thesaurus: /v1/thesaurus

    dictionary:
      base-url: https://api.dictionaryapi.dev
      endpoints:
        entries: /api/v2/entries/en

    urban:
      base-url: https://urban-dictionary7.p.rapidapi.com
      header:
        key-name: X-Rapidapi-Key
        key-value: ${URBAN_KEY}
      endpoints:
        define: /v0/define