server:
  port: 23002

spring:
  datasource:
    url: jdbc:postgresql://193.124.33.88:21002/VocabDB
    username: con
    password: conpass
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_schema: public

  data:
    redis:
      host: localhost
      port: 6379

# TODO CHANGE TO ENV VARIABLES
parser:
  api:
    ninjas:
      base-url: https://api.api-ninjas.com
      header:
        key-name: X-Api-Key
        key-value: XF2KcWY/sr7MUOuiw2OvzQ==qm1ZUa8Wi8YcDU3m
      endpoints:
        dictionary: /v1/dictionary
        thesaurus: /v1/thesaurus

    dictionary:
      base-url: https://api.dictionaryapi.dev
      endpoints:
        entries: /api/v2/entries/en

    urban:
      base-url: https://urban-dictionary7.p.rapidapi.com
      header:
        key-name: X-Rapidapi-Key
        key-value: 20822226aemsh2d2daf5147328e9p133ba8jsn342275131962
      endpoints:
        define: /v0/define